// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqGXHE9AGBfPZVztjfdmVA55DCrxlTEDE',
    appId: '1:1099393992070:web:662fae30b5f58952955807',
    messagingSenderId: '1099393992070',
    projectId: 'cookpad-flutter',
    authDomain: 'cookpad-flutter.firebaseapp.com',
    storageBucket: 'cookpad-flutter.appspot.com',
    measurementId: 'G-N40Q56E3JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rYye_-8AmqNJp44NPzgODdk3zi9OU5E',
    appId: '1:1099393992070:android:9d14af3e4f424af8955807',
    messagingSenderId: '1099393992070',
    projectId: 'cookpad-flutter',
    storageBucket: 'cookpad-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpMhahSOKBOu0pb0MWceV4F_AQ7a7gDw',
    appId: '1:1099393992070:ios:64a539ec0cd4292f955807',
    messagingSenderId: '1099393992070',
    projectId: 'cookpad-flutter',
    storageBucket: 'cookpad-flutter.appspot.com',
    iosClientId: '1099393992070-5g3g906siptbrnrufakg1q0gltcfp7nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookpadFlutter',
  );
}
